services:
  - type: web
    name: SalesLossTracker_2-0-bot
    runtime: docker
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: TZ
        value: Asia/Almaty
